[Member] 회원 이메일 발송 API #8
Team-SE-MO/semo-springboot-server pull request #14
Opened 2024-10-21 08:12 UTC by smuhsh

## #️⃣ Relationship Issues
- #8 

<br>

## 💡 Key Changes
### 1️⃣ 인증코드 발송 API
- 고객사가 비밀번호 찾기를 요청하면, 인증 코드를 이메일로 발송하는 API 추가
- API url: `[POST]  /api/v1/member/send-auth-code`

### 2️⃣ 인증 코드 검증 API
- 세션에 저장된 인증코드를 불러와 메일로 발송한 인증코드와 일치하는지 검증하는 API 추가
- API url: `[POST] /api/v1/member/verify-auth-code`

### 3️⃣ 기업등록 이메일 발송 API
- SEMO 서비스 신청을 위해 Admin 회원이 기업등록시 가입한 기업명을 확인하는 메일을 발송하는 API 추가
- API url: `[POST] /api/v1/member/send-company-registration-confirmation`

### 4️⃣ 회원가입 이메일 발송 API
- 회원이 서비스 이용을 위한 가입을 요청한 결과를 발송하는 API 추가
- API url: `[POST] /api/v1/member/send-registration-confirmation`

<br>

## ✅ Test - PostMan Tool 사용
> 테스트는 localhost의 Oracle Database의 IP, PORT, SID, USERNAME, PASSWORD 를 적용했습니다.
### 🚀 Test Connection

### 🚀 Device Register

<br>

## ➕ ETC 
- Pretendard-Regular 를 적용하려 시도했으나, 이메일 클라이언트(구글, 네이버 등)의 CSS처리방식이 자체 스타일을 적용해서 사용자 지정 CSS를 적용하지 못하는 현상이 있었습니다.

2024-10-21 12:49 UTC, IToriginal reviewed
전체적으로 중복 코드가 많고, 하드 코딩 되어 있는 로직이 많아보입니다. 메서드 분리, 클래스 분리 등 여러 방면으로 리팩토링이 필요해 보입니다. (띄어쓰기 공백 등도 포함. IDE 자동 컨벤션 적용 설정 활용 해주세요)

2024-10-21 12:49 UTC, IToriginal commented on semo-batch/src/main/resources/application.yml
> +      debug: true
batch 서버에서는 mail 사용할 일이 없는걸로 알고 있는데 batch 서버 설정에도 추가하신 이유가 있나요?

2024-10-21 12:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        }
간단한 코드 이지만 MVC 패턴에 맞지 않는 부분이 있어보입니다. 인증 코드 검증 API의 기능 단위에 인증 코드 확인 로직이 Controller의 역할일까요?
 추가로 if else로 400 예외 처리를 주셨는데, "인증 코드가 일치하지 않습니다" 이외의 예외 처리는 추가로 else if를 사용해야 할까요? 
Controller의 역할을 고민해보고 MVC 패턴 적용을 고민 해보시면 좋을 것 같습니다.

2024-10-21 12:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +            throws MessagingException, IOException {
Controller까지 throw를 올려야 하는 이유가 있을까요?

2024-10-21 12:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        return ApiResponse.successResponse(OK, "회원가입 확인 이메일 전송 성공", null);
응답 데이터가 없는 경우 상태, 메시지만 반환할 수 있는데 null을 사용할 이유가 없을 것 같네요. 다른 API 도 동일합니다.

2024-10-21 12:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
해당 기능은 Util성 기능인거 같아서 별도 클래스로 분리하면 좋을 듯 합니다.

2024-10-21 12:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        emailService.sendEmail(emailRegister, "인증 코드", authCode);
꼭 `subject`를 controller가 결정해서 service로 내려줘야 할까요? 인증 코드도 마찬가지 입니다.

2024-10-21 12:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +        }
`try-catch`문을 한번 사용하지 않고 처리 해보신 적이 있으실까요?

2024-10-21 12:49 UTC, IToriginal commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailRegister.java
> +    }
Lombok 라이브러리를 의존하고 있는데 사용을 선택적으로 하신 이유가 있나요? (아래 생성자도 포함 및 타 DTO 클래스 포함)

2024-10-21 12:49 UTC, IToriginal commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberRegisterRejection.java
> +}
필드가 1개뿐이면 DTO를 생성하지 않고 String 문자열로 전달해서 처리 가능하다 생각드네요.

다른 전달 방식도 고려해봐도 좋을 것 같습니다.

2024-10-21 12:51 UTC, IToriginal requested changes
추가로 인증 코드 발송 페이지와 다른 페이지의 색 차이가 캡처해주신 내용으로 확인되는데 동일한 스타일로 적용되면 좋을 것 같습니다.

2024-10-21 13:11 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +    @PostMapping("/send-auth-code")
api의 url 들이 특정 작업에 대한 행위에 대해 너무 자세히 명시 되어 있는데
restful하지 않다 생각합니다
리소스를 중심으로 이외의 url도 설계하면 어떨까 합니다
```
@PostMapping("/auth-code")
```

2024-10-21 16:37 UTC, dabeen-jung commented on semo-core/src/main/java/sandbox/semo/domain/form/dto/response/CompanyFormRegister.java
제가 회사 등록 폼 요청 api로 한 패키지 내 form/dto/request에 이미 이 이름을 쓰고 있어서 
가독성이 떨어지지 않을까 싶습니다.
'회사 등록'과 관련된 명칭인 CompanyRegister와 같은 명칭으로 수정하면 어떨까요?

2024-10-22 06:56 UTC, smuhsh commented on semo-batch/src/main/resources/application.yml
> +      debug: true
불필요한 설정이므로 말씀하신 부분 반영하겠습니다.

2024-10-22 06:57 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        }
컨트롤러에서 구현한 로직을 ServiceImpl 에서 구현하도록 반영했습니다.

2024-10-22 07:00 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +            throws MessagingException, IOException {
컨트롤러에서 throws MessagingException, IOException을 선언했던 배경은 책임 분리, 컴파일 타임 체크, 유연한 예외 처리와 같은 이유로, 발생할 수 있는 예외를 명확하게 선언하고, 상위 호출자가 이를 처리할 수 있도록 하기 위함이었습니다.

2024-10-22 07:00 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        return ApiResponse.successResponse(OK, "회원가입 확인 이메일 전송 성공", null);
말씀하신 부분 반영했습니다.

2024-10-22 07:08 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
generateAuthCode() 메서드를 EmailServiceImpl에 포함시키는 것은 이 기능이 이메일 인증 비즈니스 로직의 핵심적인 부분이며, 코드의 응집도를 유지하고 불필요한 복잡성을 피할 수 있다는 점에서 좋다고 생갑합니다. 별도의 유틸리티 클래스로 분리하는 것은 불필요한 추상화일 수 있기에 이메일 서비스의 일관성과 거리가 있어보입니다.

2024-10-22 07:10 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        emailService.sendEmail(emailRegister, "인증 코드", authCode);
의도는 console 에서 디버깅 용도로 활용하기 위함이었으나 서비스에서 로직을 구현했으므로 불필요한 부분입니다. 말씀하신 부분 반영하여 수정했습니다.

2024-10-22 07:11 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +        }
말씀하신 부분을 GlobalExceptionHandler 를 활용하도록 코드를 개선 하였습니다.

2024-10-22 07:13 UTC, smuhsh commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailRegister.java
> +    }
JPA 에서 객체를 빈으로 만들기 위해 기본생성자를 필요로 했고 기본생성자가 없으면 JPA가 해당 클래스를 인스턴스화 할 수 없으므로 DB에서 엔티티를 로드하거나 저장할 때 문제가 발생할 수 있다 생각했습니다. 테스트 중 기본생성자가 없었는데 이메일을 발송하지 못하여 추가했었습니다. 이 부분에 대해서 학습하겠습니다.

2024-10-22 07:20 UTC, smuhsh commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberRegisterRejection.java
> +}
MemberRegisterRejection 클래스에서 DTO를 사용한 배경에는 현재 적용된 코드들처럼 일관성을 유지하고 싶어서였습니다. 그리고 명확한 의미 전달, 입력 값 검증, 구조화된 데이터 처리 측면에서 장점이 있다 생각합니다. 비록 필드가 하나라고 하여 String으로 전달하는 것은 장기적으로 유지보수에 불리할 수 있으며, DTO를 사용하는 방식이 더 유연하고 관리하기 용이한 설계일 수 있다 생각했습니다.

2024-10-22 07:21 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +    @PostMapping("/send-auth-code")
말씀해주신 부분 반영하여 url 명을 수정했습니다.

2024-10-22 07:22 UTC, smuhsh commented on semo-core/src/main/java/sandbox/semo/domain/form/dto/response/CompanyFormRegister.java
말씀하신 부분 반영하였습니다. 좋은 네이밍이 떠오르지 않았는데 감사합니다.

2024-10-22 07:38 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        session.setAttribute("authCode", authCode);
세션에 저장한 인증 코드의 생명주기는 어떻게 되나요?

2024-10-22 07:38 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        return emailService.verifyAuthCode(inputAuthCode);
해당 검증 API도 코드 스타일을 공통적으로 맞춰주세요

2024-10-22 07:38 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +            throws MessagingException, IOException {
다른 예외를 확인해보면 결국 RuntimeException으로 처리 하셨던데 서비스 레이어에서 처리해주는 것과 어떤 차이를 가지는 거죠?
그리고, GlobalExceptionHandler에 `@RestControllerAdvice`를 사용하기 때문에 Controller에서 발생하는 예외는 모두 전역 처리가 가능 합니다.

2024-10-22 07:49 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
이메일 인증 코드 기능의 핵심 부분은 랜덤한 6자리를 뽑는 기능이 아니라, 6자리의 랜덤한 값을 확인하는 과정이 핵심 부분이라 생각합니다. (해당 메서드는 특별한 로직이 없이 단순히 **랜덤 숫자 생성** 기능으로 보입니다.) 

현재는 이메일 인증 부분에만 숫자를 생성하는 기능을 사용하시기 때문에 서비스 로직에 둬야 한다고 말씀하시는거 같은데, 코드의 응집도를 유지하고 불필요한 추상화라고 생각하신다면 public 접근 제어자를 지정할 이유도 없을 것 같다는 생각이 듭니다.

제 개인적인 생각은 6자리의 인증 숫자를 생성하는 부분은 필요하나, 핵심기능을 숫자를 확인하는 검증이며, 단순 Random 숫자라면, util로서 확장성을 생각하는게 좋을꺼 같습니다.

2024-10-22 08:05 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        emailService.sendEmail(emailRegister, authCode);
service 로직에 선언된 generateAuthCode()를 호출 응답해서 다시 그 값을 service 로직에 전달하는 것이 의미가 있나요? 비즈니스 로직 내에서 처리해도 될 것 같다는 생각이 듭니다.

2024-10-22 08:05 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
ApiResponse는 서비스 로직에서 사용하기 위한 클래스가 아닙니다. 해당 로직은 컨트롤러를 서비스에서 실행하는 것과 동일해 보이네요. 다른 도메인처럼 예외 처리 클래스를 만들고 처리해서 예외를 관리하기 용기하게 해주세요.

2024-10-22 08:05 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +        }
예외 처리를 `GlobalExceptionHandler`는 Controller 단의 예외를 가로채서 예외를 발생시키는겁니다. 
수정하신 부분은 그냥 예외처리를 삭제 처리 하신걸로 보입니다.

2024-10-22 08:10 UTC, IToriginal requested changes

2024-10-22 08:10 UTC, IToriginal commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailRegister.java
> +    }
수정이 안되어 있네요. Lombok 어노테이션을 학습하신 후 수정 부탁드립니다.
package sandbox.semo.domain.member.dto.response; 포함입니다.

2024-10-22 08:10 UTC, IToriginal commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberRegisterRejection.java
> +}
좋은 접근은 맞습니다. 근데 email 필드 한개를 전달하는데 클래스에 담는 과정이 필요한지에 대한 생각입니다. 명확한 전달이 목적이라면 email의 변수명을 좀더 명확하게 할 수 있을 것 같네요.

2024-10-22 08:11 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +    @PostMapping("/send-auth-code")
구분이 어려운 경우를 예외로 RestfulAPI의 url은 공통적인 url부분에서 2번의 깊이를 주지 않습니다. 네이밍에 좀 더 고민이 필요해보입니다.

2024-10-22 08:13 UTC, IToriginal commented
앞선 리뷰에서 말씀드린 중복 코드는 `EmailServiceImpl` 클래스에 메서드들을 보면 지속적으로 같은 역할의 중복된 코드가 많이 보입니다. 메서드 분리를 고려해주시면 감사하겠습니다.

2024-10-22 15:40 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +            throws MessagingException, IOException {
@smuhsh 
`try-catch` 사용을 지양하고 간결한 코드로 리팩토링하기 위해 추가로 코멘트를 남겨드립니다.

`MessagingException`과 `IOException` 그리고 `SQLException`과 같은 예외는 말씀하신 것 처럼 체크 예외(컴파일 타임 체크)로, 반드시 처리해야 하는 예외입니다. 그런데 말씀하신 것과는 다르게 Controller, Service 두 곳에서 예외 처리가 이루어져있었고, 말씀하신 부분과는 다르게 예외를 명확하게 선언했다 보기는 어려웠습니다.

제가 코멘트를 남긴 이유는, `Controller`에서 `throws`를 사용해 예외를 상위로 전파했음에도 불구하고, `Service` Layer에서 여전히 `try-catch`로 예외를 처리하고 있었기 때문에 석현님의 예외 처리 의도를 파악할 수 없었습니다.

`Controller`에서 `throws`를 사용하면 `Service` 레이어에서 발생한 예외를 상위 레이어(`Controller`)로 넘긴다는 의미입니다. 따라서 `Service` 레이어에서 `try-catch`를 사용할 필요가 없습니다. (상위 레이어에서 예외 처리가 이루어지기 때문)

그럼 해당 코멘트를 해결하기 위해서는 아래의 내용을 참고하시면 됩니다.
**[1번 제안 방법]**
>`Service` 레이어에서 `try-catch`를 제거하고, `Controller` 레이어에서 `@RestControllerAdvice`가 적용된 `GlobalExceptionHandler`를 통해 체크 예외(`MessagingException`, `IOException`)를 처리

이렇게 하면 Service 레이어에서는 예외를 던지기만 하고, Controller 레이어에서 예외를 처리할 수 있습니다.

**[2번 제안 방법]**
> `Controller`의 throws를 제거하고 Service에서 `try-catch`를 사용

결국, 제가 드린 코멘트의 핵심은 체크 예외를 어느 계층에서 처리할지를 명확히 해야 한다는 점입니다. 예외 처리를 Controller에서 할 계획이라면, Service 레이어에서는 try-catch 없이 예외를 상위로 던지고, GlobalExceptionHandler에 체크 예외 처리 로직을 추가하는 방식이 더 적절하다고 생각했습니다.

> 개인적으로는 저는 가독성도 좋지 않고 타 예외처리의 방식과 공통성이 없는 `try-catch` 사용을 지양합니다. 물론 자원을 해제시켜줄 필요가 있는 `SQLExcpetion`은 `try-with-resources`를 사용하여 처리하고, `try-catch`를 사용할 수 밖에 없는 마지막 시도에만 사용합니다.

2024-10-23 00:28 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +            throws MessagingException, IOException {
고맙습니다 알려주신 방법 적용해서 개선해보겠습니다

2024-10-23 03:14 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        session.setAttribute("authCode", authCode);
5분으로 설정했습니다

2024-10-23 03:17 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
인증코드를 이메일로 발송하는 과정은 인증코드 생성, 인증코드 이메일 발송, 생성된 인증코드를 세션에 저장하는 순서로 처리되도록 메서드를 구현하였습니다. 그리고 인증코드를 반환 후 검증하는 로직을 거치는데 세션 인증시간을 5분으로 설정해두었습니다.

2024-10-23 03:18 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +        }
말씀하신 부분을 EmailBusinessException 을 통해 개선하였습니다. 상황별로 EmailErrorCode 에서 현재 어떤 예외가 발생했는지 확인할 수 있습니다.

2024-10-23 03:18 UTC, smuhsh commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/request/EmailRegister.java
> +    }
해당 부분을 수정했습니다.

2024-10-23 03:19 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +    @PostMapping("/send-auth-code")
URL을 수정했습니다.

2024-10-23 03:20 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        emailService.sendEmail(emailRegister, authCode);
좋은 의견 주셔서 감사합니다. 말씀하신 방향으로 코드를 개선했습니다.

2024-10-23 03:20 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
말씀하신 부분에 대하여 이메일에 대한 예외 클래스를 생성해서 관리하였습니다.

2024-10-24 16:08 UTC, dabeen-jung commented
노션의 api명세서 작성 및 수정 해서
결과 응답값과 넣어줘야 하는 예시값도 명시한 후 리뷰 요청 부탁드리겠습니다.ᐟ.ᐟ @smuhsh

2024-10-25 01:47 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    public ApiResponse<String> sendEmail(@RequestBody EmailRegister emailRegister) {
DTO 단에서 @NotNull을 쓰셨는데
유효성 검사를 위해 @Valid와 같은 어노테이션을 추가하시면 어떨까요?

2024-10-25 01:50 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    //public ApiResponse<String> sendCompanyRegistrationConfirmationEmail(@RequestBody CompanyFormList companyFormList) {
이부분 주석이 제대로 제거가 안된 것 같습니다!

2024-10-25 02:02 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    public ApiResponse<String> sendCompanyRegistrationConfirmationEmail(@RequestBody CompanyFormInfo companyFormInfo) {
여기에서 사용한 CompanyFormInfo는 **'회사요청 폼 목록조회 API'** 로 이용하는
 응답 DTO인데 이를 요청 DTO로 활용하신 이유가 있으실까요?

2024-10-25 02:09 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    //public ApiResponse<String> sendCompanyRegistrationConfirmationEmail(@RequestBody CompanyFormList companyFormList) {
push 가 제대로 안되었던 것 같습니다. 다시 올렸습니다.

2024-10-25 02:09 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    public ApiResponse<String> sendCompanyRegistrationConfirmationEmail(@RequestBody CompanyFormInfo companyFormInfo) {
이 API의 흐름은 
이미 `Companies` 테이블에 생성된 회사의 등록을 `CompanyForm`을 등록한 요청자에게 알림을 보내는 API로 이해하는데 

여기서 사용되는 ownerName, companyName을 쓰시려면 
> 현재 쓰고 계신 url 상의 companyId가 아무런 역할을 하고 있지 않으니
이 대신 승인이 완료된(회사 등록 - 관리자 승인처리 API 응답 값) `formId `등을 `@RequestParam`등으로 받아오는 것은 어떨까 합니다

2024-10-25 02:13 UTC, dabeen-jung commented on semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
> +    MemberRegister findByEmail(String email);
얘는 어디서 쓰이는건지 궁금합니다!

2024-10-25 02:19 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    public ApiResponse<String> sendEmail(@RequestBody EmailRegister emailRegister) {
말씀하신 부분처럼 컨트롤러에서 유효성 검사를 수행하지 않으면 유효하지 않은 데이터가 서비스 계층까지 전달될 수 있으므로 해당 사항을 반영하여 코드를 개선했습니다.

2024-10-25 02:19 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +}
IMO....
회원가입이 반려되었으니 `memberform `테이블에 승인상태가 '`DENIED`'인지 확인 후 보내주면 더 좋을 것 같다는 생각이 듭니다!

2024-10-25 02:22 UTC, dabeen-jung requested changes
몇몇 부분만 수정해주시면 더더욱 좋은 코드가 될 것 같습니다! 👍
API 명세서 부분 노션에서 새로 정의된 부분과 기존과 달라진 API 들은 반영해주시면 감사하겠습니다 :)

2024-10-25 06:07 UTC, smuhsh commented
> 노션의 api명세서 작성 및 수정 해서 결과 응답값과 넣어줘야 하는 예시값도 명시한 후 리뷰 요청 부탁드리겠습니다.ᐟ.ᐟ @smuhsh

기능구현이 완료되어서 명세서 작성하겠습니다

2024-10-25 06:09 UTC, smuhsh commented on semo-core/src/main/java/sandbox/semo/domain/member/repository/MemberRepository.java
> +    MemberRegister findByEmail(String email);
현재 사용되지 않는 필드라 삭제했습니다

2024-10-25 06:10 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    public ApiResponse<String> sendCompanyRegistrationConfirmationEmail(@RequestBody CompanyFormInfo companyFormInfo) {
오전 회의에서 말씀하신 부분 반영하여 기능구현 완료했습니다 (formId으로 조회 후 Approved 에게만 전송됨)

2024-10-25 10:32 UTC, dabeen-jung requested changes
회원가입 요청 dto로 같은 파일 이름을 쓰고 있습니다 
파일명이 좀 더 명확하면 좋을거 같아요

2024-10-25 10:46 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        session.setAttribute("authCode", authCode);
5분 이후에 session에 추가 된 인증 코드는 삭제가 된다는 의미가 맞나요?

2024-10-25 10:50 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/member/service/EmailServiceImpl.java
> +    }
제 코멘트의 내용은 util성 기능에 대한 문제호 분리하는게 맞지 않는가에 대한 의견이였습니다.

2024-10-26 14:50 UTC, IToriginal commented on semo-api/src/main/resources/templates/company-registration.html
> +    }
제가 전달들은 바는 폰트 적용이 안된걸로 알고 있는데 font-family 적용이 됐을까요?

2024-10-27 07:21 UTC, dabeen-jung commented
api 명세서 상에 작성하신 4개의 api가 제대로 작성이 안되어 있는 것 같습니다
제목이랑 내용 부분이 전부 작성된 상태신가요?
이메일 인증코드 발송 외에 이메일 인증코드 검증 api는 작성하신건가요?? @smuhsh

2024-10-27 07:34 UTC, taeyeon721 requested changes

2024-10-27 07:34 UTC, taeyeon721 commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    }
현재 inputAuthCode만 받아서는 인증 요청이 어느 사용자에게 해당되는지 알기 어려울 것 같습니다. 인증 코드를 특정 사용자에게 매칭하려면 이메일 같은 추가 정보를 함께 받아야 할 것 같습니다.

2024-10-28 09:04 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/member/controller/EmailController.java
> +        session.setAttribute("authCode", authCode);
sendAuthCode 메서드에서 generateAuthCode() 를 호출해 6자리 인증 코드를 생성했고 생성된 인증코드는
session.setAttribute("authCode", authCode); 를 통해 HttpSession 객체에 "authCode" 라는 키로 저장됩니다.
그리고 코드에서 세션의 만료 시간이나 저장시간에 대한 설정은 명시적으로 정의되지 않았지만 이 경우 스프링부트 기본 세션 만료 시간 설정에 따라 인증코드는 세션 만료 시점까지 유지됩니다.
스프링부트는 기본 세션 타임아웃 시간은 30분 입니다. 저는 application.yml 에서 5분으로 설정했고 인증코드는 세션이 만료됨과 동시에 삭제되도록 구현했습니다.

2024-10-28 09:46 UTC, smuhsh commented on semo-api/src/main/resources/templates/company-registration.html
> +    }
사용자 정의 css가 적용되지 않는 이슈가 있었지만 전송하는데 문제가 없어서 수정하지는 않았습니다. 현재 불필요한 부분이므로 바로 조치하겠습니다.

2024-10-29 08:30 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +    }
사용자별 이메일로 발송된 인증코드를 세션에 담아 소멸시 까지 유지하도록 작성하였습니다.

2024-10-29 08:31 UTC, smuhsh commented
> api 명세서 상에 작성하신 4개의 api가 제대로 작성이 안되어 있는 것 같습니다 제목이랑 내용 부분이 전부 작성된 상태신가요? 이메일 인증코드 발송 외에 이메일 인증코드 검증 api는 작성하신건가요?? @smuhsh

메일발송이 apiType 에 따른 동적 URL 으로 변경되었고 해당부분 반영하여 명세서 작성하였습니다.

2024-10-29 11:10 UTC, IToriginal requested changes
리뷰 해주는 팀원들을 위해 코드 정리에 신경써주세요.

2024-10-29 11:10 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +        return emailData;
Map을 반환타입으로 지정한 이유가 있나요?
심지어 반환 받은 걸 사용하지 않고 있는 걸로 보이는데 확인이 필요해 보이네요.

2024-10-29 11:10 UTC, IToriginal commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberRegisterRejection.java
어디에 사용되는 클래스 인가요?

2024-10-29 11:10 UTC, IToriginal commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberRegister.java
어디에 사용되는 클래스 인가요?

2024-10-29 11:10 UTC, IToriginal commented on semo-batch/src/main/resources/application.yml
> +    org.springframework.security: DEBUG
머지막 개행 한줄 추가해주세요

2024-10-29 11:10 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +                .orElseThrow(() -> new EmailBusinessException(EmailErrorCode.MEMBER_NOT_FOUND)); // 값이 없을 경우 예외 처리
주석 제거 필요합니다. 불필요한 주석입니다.

2024-10-29 11:10 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    private Map<String, Object> sendMemberRegistrationConfirmationEmail(String loginId) {
반환 타입 확인 필요합니다.

2024-10-29 11:10 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    }
라인 장리 필요합니다. 불필요한 엔터는 삭제해서 붙혀주세요. 오히려 가독성이 떨어집니다.

2024-10-29 12:57 UTC, IToriginal requested changes

2024-10-29 12:57 UTC, IToriginal commented on build.gradle
> +}
마지막 개행 필요

2024-10-29 12:57 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +        emailService.verifyAuthCode(emailRequest.getEmail(), emailRequest.getAuthCode());
이메일 전송 API와 동일한 방식으로 공통된 개발을 부탁드립니다.
곧바로 위에서 DTO를 바로 전달하고, 아래에서는 풀어서 전달하고, 통일성이 없어요.

requestDTO는 전달 객체로서 그대로 전달하는게 용도에 맞게 사용하는 것 같습니다.

2024-10-29 12:57 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailService.java
> +    void processEmailRequest(EmailSend request);
Controller에서 사용되는 Service 기능은 2가지 뿐인데  서비스 레이어 내에서 호출하는 메서드를 남겨두신 이유가 있나요?

2024-10-29 12:57 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
리뷰어는 보통 사람이기 때문에 위에서 아래로 코드를 주로 확인합니다. 이에 맞게 아래와 같이 코드 정리를 부탁합니다.

```java
private final .... ;

@Override 
public ...(...) {
    ... method1;
    ... method2;
    ...
}

private ... method1() {
    ...
}

private ... method2() {
    ...
}

@Override
public ... (...) { ... }

```

2024-10-29 12:57 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    }
메서드 네이밍이 겹칩니다. 수정이 필요해요

2024-10-29 12:57 UTC, IToriginal commented on semo-api/src/main/resources/application.yml
> +      timeout: 5m
인증 코드 5분에 대해서 다른 방식을 생각해보셔야 할 것 같네요. `application.yml`에 session timeout을 설정하면 메일 인증 코드 뿐만 아니라 모든 세션에 대해 5분의 리밋을 적용하게 됩니다. 이는 현재 적용되어 있는 로그인에도 영향을 미치게 되므로, 로그인한 이용하는 세션에 5m 뒤 세션이 만료되어 재로그인을 해야합니다.

2024-10-30 01:06 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/controller/EmailController.java
> +        emailService.verifyAuthCode(emailRequest.getEmail(), emailRequest.getAuthCode());
말씀 감사합니다. 주목적에 맞게 코드를 개선했습니다.

2024-10-30 01:08 UTC, smuhsh commented on build.gradle
> +}
말씀하신 부분 반영하였습니다.

2024-10-30 01:18 UTC, smuhsh commented on semo-core/src/main/java/sandbox/semo/domain/member/dto/response/MemberRegisterRejection.java
DTO 가 개선되어 현재 불필요한 코드이므로 삭제했습니다.

2024-10-30 01:20 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailService.java
> +    void processEmailRequest(EmailSend request);
서비스 기능의 의도를 고려하지 못했고 내부로직에서만 사용되는걸 확인했습니다. 코드를 개선했습니다.

2024-10-30 01:23 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
흐름에 맞게 코드 순서를 변경했습니다.

2024-10-30 01:24 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    }
명확한 의미전달을 위해 네이밍을 개선했습니다.

2024-10-30 02:48 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    private Map<String, Object> sendMemberRegistrationConfirmationEmail(String loginId) {
![image](https://github.com/user-attachments/assets/9c6b6d59-3c13-4bf3-b38e-c8b83207d0f2)

post 전송시 어떤 값이 반환되는지 알기위해 필요합니다.

2024-10-30 03:01 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +        return emailData;
processEmailRequest 에서 post 전송시 company, member 의 데이터를 반환하기 위해 필요하며 emailData 를 통해 return 하고 있습니다. emailData 는 companyName, ownerName, loginId, currentDate 등의 정보를 담고있습니다.

2024-10-30 05:42 UTC, smuhsh commented on semo-batch/src/main/resources/application.yml
> +    org.springframework.security: DEBUG
반영했습니다

2024-10-30 05:44 UTC, smuhsh commented on semo-api/src/main/resources/application.yml
> +      timeout: 5m
전체 세션에 영향없이 발송된 인증코드의 세션상태에만 생명주기를 설정하였고 테스트하여 확인 완료 하였습니다.

2024-10-30 10:52 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    }
간결한 네이밍으로 개선했습니다

2024-10-31 02:14 UTC, IToriginal commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +        }
동일한 예외를 반환하고 있어서 else if로 굳이 나눌 필요없이 if() 에 또는(||) 으로 처리해도 무관해보입니다.
if 괄호 안의 조건식이 만약 길이가 길고 가독성을 해친다는 생각이 드시면 검증 메소드로 분리해주셔도 될 듯하구요.

2024-10-31 03:01 UTC, smuhsh commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +        }
반영완료 하였습니다.

2024-10-31 05:15 UTC, IToriginal approved these changes
고생 많으셨어요! 👍🏻

2024-10-31 05:28 UTC, dabeen-jung commented on semo-api/src/main/java/sandbox/semo/application/email/service/EmailServiceImpl.java
> +    }
코드가 훨씬 읽기 좋고 깔끔해졌네요!

2024-10-31 05:29 UTC, taeyeon721 approved these changes
수고하셨습니다.

2024-10-31 06:37 UTC, juneheel approved these changes

2024-10-31 06:37 UTC, dabeen-jung approved these changes

2024-10-31 06:38 UTC, merged